# Generated by Django 2.2.5 on 2022-09-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebTienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.ManyToManyField(to='ProyectoWebTienda.Categoria'),
        ),
    ]
