# Generated by Django 2.2.5 on 2022-09-24 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebTienda', '0002_auto_20220924_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='categoria',
            new_name='categorias',
        ),
    ]
