# Generated by Django 2.2.5 on 2022-09-25 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebTienda', '0004_auto_20220925_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='categorias',
            new_name='categoria',
        ),
    ]
