# Generated by Django 2.2.5 on 2022-09-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebServicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
