# Generated by Django 2.2.5 on 2022-09-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebServicios', '0002_auto_20220914_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='imagen',
            field=models.ImageField(upload_to='servicios'),
        ),
    ]
