# Generated by Django 2.2.5 on 2022-09-15 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebBlog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='contenido',
        ),
    ]
